### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kontra13** [core-infra-svcs/terraform-provider-meraki#307]
As of just this morning, without changing any of our underlying code configuration, I started getting a runtime error from the v0.6.1 plugin.  Here is the output:

Stack trace from the terraform-provider-meraki_v0.6.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6e7c4e]

goroutine 38 [running]:
github.com/core-infra-svcs/terraform-provider-meraki/tools.HttpDiagnostics(0x0)
        github.com/core-infra-svcs/terraform-provider-meraki/tools/http.go:12 +0x4e
github.com/core-infra-svcs/terraform-provider-meraki/internal/provider.(*OrganizationsDataSource).Read(0xc000012068, {0x21a03a0, 0xc000624e10}, {{{{0x21a5630, 0xc000625770}, {0x1c60140, 0xc000625680}}, {0x21a7968, 0xc000356100}}, {{{0x0, ...}, ...}, ...}}, ...)
        github.com/core-infra-svcs/terraform-provider-meraki/internal/provider/organizations_data_source.go:138 +0x376
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc0001af040, {0x21a03a0, 0xc000624e10}, 0xc000624ea0, 0xc0005b76d8)
        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/fwserver/server_readdatasource.go:79 +0x4ae
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc0001af040, {0x21a03a0?, 0xc000624c00?}, 0xc0004780c0)
        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/proto6server/server_readdatasource.go:55 +0x42f
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc0001cedc0, {0x21a03a0?, 0xc000624240?}, 0xc0004ea640)
        github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/tf6server/server.go:685 +0x432
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x1f2a300?, 0xc0001cedc0}, {0x21a03a0, 0xc000624240}, 0xc000600180, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:572 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000197000, {0x21a03a0, 0xc0006241b0}, {0x21a5bb8, 0xc00038a1a0}, 0xc000621200, 0xc0002e9740, 0x3017d20, 0x0)
        google.golang.org/grpc@v1.61.0/server.go:1385 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc000197000, {0x21a5bb8, 0xc00038a1a0}, 0xc000621200)
        google.golang.org/grpc@v1.61.0/server.go:1796 +0x1031
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.61.0/server.go:1029 +0x91
created by google.golang.org/grpc.(*Server).serveStreams.func2
        google.golang.org/grpc@v1.61.0/server.go:1040 +0x145
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6e7c4e]

goroutine 65 [running]:
github.com/core-infra-svcs/terraform-provider-meraki/tools.HttpDiagnostics(0x0)
        github.com/core-infra-svcs/terraform-provider-meraki/tools/http.go:12 +0x4e
github.com/core-infra-svcs/terraform-provider-meraki/internal/provider.(*OrganizationsDataSource).Read(0xc0003b8040, {0x21a03a0, 0xc0000b2d80}, {{{{0x21a5630, 0xc0000b3620}, {0x1c60140, 0xc0000b3530}}, {0x21a7968, 0xc000572180}}, {{{0x0, ...}, ...}, ...}}, ...)
        github.com/core-infra-svcs/terraform-provider-meraki/internal/provider/organizations_data_source.go:138 +0x376
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc0001af040, {0x21a03a0, 0xc0000b2d80}, 0xc0000b2e10, 0xc0001676d8)
        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/fwserver/server_readdatasource.go:79 +0x4ae
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc0001af040, {0x21a03a0?, 0xc0000b2c30?}, 0xc00007a2c0)
        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/proto6server/server_readdatasource.go:55 +0x42f
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc0001cedc0, {0x21a03a0?, 0xc0000b22a0?}, 0xc0000d0140)
        github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/tf6server/server.go:685 +0x432
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x1f2a300?, 0xc0001cedc0}, {0x21a03a0, 0xc0000b22a0}, 0xc0000da000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:572 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000197000, {0x21a03a0, 0xc0000b2210}, {0x21a5bb8, 0xc0001afd40}, 0xc0000d8000, 0xc0002e9740, 0x3017d20, 0x0)
        google.golang.org/grpc@v1.61.0/server.go:1385 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc000197000, {0x21a5bb8, 0xc0001afd40}, 0xc0000d8000)
        google.golang.org/grpc@v1.61.0/server.go:1796 +0x1031
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.61.0/server.go:1029 +0x91
created by google.golang.org/grpc.(*Server).serveStreams.func2
        google.golang.org/grpc@v1.61.0/server.go:1040 +0x145

Error: The terraform-provider-meraki_v0.6.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by kontra13** [comment]
Must have just been the Meraki API having issues, as today I was unable to reproduce the error.
